"""Bounded chat access; source text is never an executable instruction."""

from typing import Protocol


class ChatDataError(RuntimeError):
    def __init__(self, code: str, status: int = 503):
        self.code, self.status = code, status
        super().__init__(code)


class ChatDataSource(Protocol):
    def configure(self, base_url: str, token: str) -> dict: ...

    def request(self, route: str, body: dict | None = None, **query) -> dict: ...


CONTRACT = "CHAT_DATA_CONTRACT_V1"


class ChatCacheStore(Protocol):
    def get(self, key, default=None): ...
    def put(self, key, value): ...
    def activate(self, dataset): ...
    def receive(self, dataset, items, **options): ...
    def create_scope(self, dataset, scope, snapshot): ...
    def reset_scope(self, key): ...
    def enable_scope(self, key, enabled): ...
    def scopes(self): ...
    def scope(self, key): ...
    def scope_error(self, key, code): ...
    def process(self, limit=100): ...
    def retry_index(self): ...
    def health(self): ...
    def search(self, scope, limit=50, cursor=None): ...
    def context(self, rid, before, after): ...
    def job(self, jid, state=None, value=None, error=None): ...
