from typing import Protocol


class ChatFollowupRepository(Protocol):
    def admission(self, key: str, dataset: str): ...
    def save_admission(self, value: dict): ...
    def source(self, key: str): ...
    def for_event(self, event_id: str): ...
    def save_source(self, key: str, value: dict): ...
    def items(self, limit: int, offset: int = 0): ...
    def effect_exists(self, key: str) -> bool: ...
    def effect(self, key: str, event_id: str, details: dict): ...
    def job(self, job_id: str): ...
    def save_job(self, job_id: str, state: str, value: dict): ...
    def jobs(self): ...
