from __future__ import annotations
from datetime import datetime
from typing import Protocol
from allday_asr.v3.domain.models import (
    Artifact,
    AudioAsset,
    AudioReplica,
    CaptureSegment,
    Device,
    ProcessingRun,
    RecordingSession,
    SessionManifest,
)
from allday_asr.v3.domain.processing import (
    ArtifactInvalidation,
)


class RecordingCatalogRepository(Protocol):
    def add_session(self, session: RecordingSession) -> bool: ...
    def add_asset(self, asset: AudioAsset) -> bool: ...
    def add_replica(self, replica: AudioReplica) -> bool: ...
    def add_segment(self, segment: CaptureSegment) -> bool: ...
    def add_manifest(self, manifest: SessionManifest) -> bool: ...
    def find_session_by_legacy_ref(
        self, legacy_ref: str
    ) -> RecordingSession | None: ...
    def find_session_by_manifest_sha256(
        self, sha256: str
    ) -> RecordingSession | None: ...
    def tombstone_duplicate_session(
        self,
        session_id: str,
        canonical_session_id: str,
        tombstoned_at: datetime,
    ) -> int | None: ...
    def find_asset_by_sha256(self, sha256: str) -> AudioAsset | None: ...
    def get_session(self, session_id: str) -> RecordingSession: ...


class DeviceRepository(Protocol):
    def add(self, device: Device) -> bool: ...


class ProcessingRunRepository(Protocol):
    def add(self, run: ProcessingRun) -> bool: ...
    def find_by_legacy_ref(self, legacy_ref: str) -> ProcessingRun | None: ...
    def get(self, run_id: str) -> ProcessingRun: ...


class ArtifactRepository(Protocol):
    def add(self, artifact: Artifact) -> bool: ...
    def list_active_for_run(self, run_id: str) -> tuple[Artifact, ...]: ...
    def add_dependency(
        self, artifact_id: str, input_type: str, input_id: str, input_revision: int
    ) -> bool: ...
    def dependent_ids(self, input_type: str, input_id: str) -> tuple[str, ...]: ...
    def invalidate(self, event: ArtifactInvalidation) -> bool: ...
