from __future__ import annotations
from typing import Any, Protocol
from allday_asr.v3.ports.speaker_embeddings import SpeakerTrackInput


class PeopleRepository(Protocol):
    def sample_plans(self, session_id: str, model: str, version: str) -> tuple: ...
    def enqueue_samples(self, session_id: str) -> None: ...
    def refresh_sample_model(self, model: str, version: str) -> None: ...
    def claim_sample_job(self, now: float, token: str) -> dict | None: ...
    def finish_sample_job(self, session_id: str, generation: int, token: str,
                          status: str, reason: str, now: float) -> None: ...
    def sample_job(self, session_id: str) -> dict: ...
    def select_sample_set(self, plan) -> bool: ...

    def sample_set_exists(self, key: str) -> bool: ...
    def record_sample_set(self, plan: Any, embedding: Any, prototype_id: str, now: str) -> None: ...
    def add_manual_group(self, cluster_id: str, track_ids: tuple[str, ...], label: str,
                         actor: str, operation_id: str, created_at: str) -> None: ...

    def analysis_inputs(self, session_id: str) -> tuple[SpeakerTrackInput, ...]: ...
    def manual_track_cluster(self, track_id: str) -> str | None: ...
    def annotation_samples(self, utterance_id: str) -> tuple[dict, ...]: ...
    def confirmed_enrollment_input(
        self,
        session_id: str,
        speaker_track_id: str,
        windows: tuple[tuple[int, int], ...],
    ) -> dict[str, Any]: ...
    def person_kind(self, person_id: str) -> str: ...
    def self_person_id(self) -> str | None: ...
    def start_run(
        self,
        run_id: str,
        session_id: str,
        model: str,
        model_version: str,
        policy: dict[str, Any],
        track_count: int,
        created_at: str,
    ) -> None: ...
    def finish_run(
        self, run_id: str, status: str, completed_at: str, error: str | None
    ) -> None: ...
    def cluster_vectors(
        self, model: str, model_version: str
    ) -> tuple[tuple[str, tuple[float, ...]], ...]: ...
    def person_vectors(
        self, model: str, model_version: str
    ) -> tuple[tuple[str, tuple[float, ...]], ...]: ...
    def identity_policies(self) -> dict[str, dict[str, Any]]: ...
    def identity_policy(self, person_id: str) -> dict[str, Any]: ...
    def add_identity_policy_revision(
        self, person_id: str, **values: Any
    ) -> dict[str, Any]: ...
    def unlinked_cluster_embeddings(
        self, session_id: str | None = None
    ) -> tuple[dict[str, Any], ...]: ...
    def set_cluster_suggestion(
        self,
        cluster_id: str,
        person_id: str | None,
        confidence: float | None,
        updated_at: str,
    ) -> None: ...
    def record_match_decision(self, **values: Any) -> None: ...
    def prototype_retraction_target(self, prototype_id: str, person_id: str) -> dict: ...

    def prototype_candidate(self, prototype_id: str) -> dict[str, Any]: ...
    def latest_prototype_review(
        self, prototype_id: str, person_id: str
    ) -> dict[str, Any] | None: ...
    def add_prototype_review(self, **values: Any) -> dict[str, Any]: ...
    def prototype_review_examples(self, person_id: str) -> dict[str, Any]: ...
    def list_review_candidates(
        self, person_id: str | None, status: str | None, limit: int
    ) -> tuple[dict[str, Any], ...]: ...
    def record_embedding(self, **values: Any) -> None: ...
    def list_people(self) -> tuple[dict[str, Any], ...]: ...
    def list_clusters(
        self, status: str | None, limit: int
    ) -> tuple[dict[str, Any], ...]: ...
    def cluster_detail(self, cluster_id: str) -> dict[str, Any]: ...
    def create_person(
        self, person_id: str, display_name: str, kind: str, created_at: str
    ) -> None: ...
    def import_person(
        self,
        person_id: str,
        display_name: str,
        kind: str,
        aliases: tuple[str, ...],
        relationship_labels: tuple[str, ...],
        actor: str,
        created_at: str,
    ) -> bool: ...
    def label_cluster(
        self,
        cluster_id: str,
        person_id: str,
        actor: str,
        operation_id: str,
        created_at: str,
        *,
        source: str = "human",
        confidence: float = 1.0,
        promote_candidates: bool = False,
    ) -> tuple[str | None, tuple[str, ...], tuple[str, ...]]: ...
    def merge_clusters(
        self,
        source_cluster_ids: tuple[str, ...],
        target_cluster_id: str,
        actor: str,
        operation_id: str,
        created_at: str,
    ) -> None: ...
    def split_cluster(
        self,
        cluster_id: str,
        speaker_track_ids: tuple[str, ...],
        new_cluster_id: str,
        new_label: str,
        actor: str,
        operation_id: str,
        created_at: str,
    ) -> None: ...
    def ignore_cluster(
        self,
        cluster_id: str,
        reason: str,
        actor: str,
        operation_id: str,
        created_at: str,
    ) -> None: ...
    def undo(
        self, cluster_id: str, actor: str, undo_operation_id: str, created_at: str
    ) -> dict[str, Any]: ...
    def events_referencing(self, reference_id: str) -> tuple[dict[str, Any], ...]: ...
    def events_by_ids(
        self, event_ids: tuple[str, ...]
    ) -> tuple[dict[str, Any], ...]: ...
    def cluster_evidence_ids(
        self, cluster_id: str, session_id: str | None = None
    ) -> tuple[str, ...]: ...


class PersonMemoryRepository(Protocol):
    def profile(self, person_id: str) -> dict[str, Any]: ...
    def update_profile(
        self,
        person_id: str,
        display_name: str,
        aliases: tuple[str, ...],
        relationship_labels: tuple[str, ...],
        notes: str,
        actor: str,
        created_at: str,
    ) -> dict[str, Any]: ...
    def event_sources(self, person_id: str) -> tuple[dict[str, Any], ...]: ...
    def current_memory(self, memory_id: str) -> dict[str, Any]: ...
    def add_revision(self, **values: Any) -> dict[str, Any]: ...
    def person_detail(self, person_id: str, limit: int = 200) -> dict[str, Any]: ...
    def list_current(
        self, person_id: str, *, limit: int, include_inactive: bool
    ) -> tuple[dict[str, Any], ...]: ...
    def summary_counts(self) -> dict[str, dict[str, Any]]: ...
    def revise_status(
        self,
        memory_id: str,
        status: str,
        actor: str,
        operation_id: str,
        operation_kind: str,
        created_at: str,
    ) -> dict[str, Any]: ...
    def undo(
        self, memory_id: str, actor: str, operation_id: str, created_at: str
    ) -> dict[str, Any]: ...
    def reconcile_identity(
        self,
        cluster_id: str,
        old_person_id: str | None,
        new_person_id: str | None,
        actor: str,
        created_at: str,
    ) -> int: ...


class InsightRepository(Protocol):
    def event_sources(self) -> tuple[dict[str, Any], ...]: ...
    def person_interactions(self, person_id: str) -> tuple[dict[str, Any], ...]: ...
    def person_profile(self, person_id: str) -> dict[str, Any]: ...
    def next_daily_revision(self, summary_id: str) -> int: ...
    def add_daily(self, **values: Any) -> None: ...
    def daily(self, summary_id: str) -> dict[str, Any]: ...
    def list_daily(self, limit: int) -> tuple[dict[str, Any], ...]: ...
    def next_relationship_revision(self, report_id: str) -> int: ...
    def add_relationship(self, **values: Any) -> None: ...
    def relationship(self, report_id: str) -> dict[str, Any]: ...
    def list_relationships(
        self, person_id: str | None, limit: int
    ) -> tuple[dict[str, Any], ...]: ...
    def add_evidence(self, *values: Any) -> bool: ...
    def add_operation(self, *values: Any, **options: Any) -> None: ...
    def latest_relationship_operation(
        self, report_id: str
    ) -> dict[str, Any] | None: ...
    def evidence_revisions(
        self, event_ids: tuple[str, ...], utterance_ids: tuple[str, ...]
    ) -> tuple[dict[str, int], dict[str, int]]: ...
